baseurl = "https://halloween-bash.netlify.app"
title = "Tostadas XV!"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->Decemeber 19, 2020!<!--]--><br/><!--[-->Be there or be square.<!--]-->'
  logo = "fa-birthday-cake"
  copyright = "Beto"


[languages]
[languages.en]
languageName = "English"
weight = 1
