baseurl = "http://example.org"
title = "You're Invited!"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->Saturday, November 17th<!--]--><br/>
                <!--[-->Be there or be square.<!--]-->'
  logo = "fa-diamond"
  copyright = "Beto"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1
