baseurl = "https://ramon-halloween-bash.netlify.app"
title = "Ramon's Halloween Bash"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->Friday, October 30th.<!--]--><br/>
                <!--[-->Be there or be square.<!--]-->'
  logo = "fa-beer"
  copyright = "Beto"


[languages]
[languages.en]
languageName = "English"
weight = 1
