baseurl = "https://halloween-bash.netlify.app"
title = "Ariana Rubi's XV!"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = """Decemeber 19, 2020 <p /> &#x25A1; Be there or be square &#x25A1;"""
  logo = "fa-birthday-cake"
  copyright = "Beto"

[languages]
[languages.en]
languageName = "English"
weight = 1
